### ISSUE TITLE
Diagram center  command do not show the center of the diagram

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/yangster#24] opened 2017-10-23 15:11 UTC
Diagram -> Center:  Seems the command does different things depending where the last user focus was in the diagram. It seems it center the last module the user selected. No indication on the diagram to show what was the last user selection.
![peek 2017-10-23 center](https://user-images.githubusercontent.com/419051/31896721-7c04ac0e-b7e2-11e7-9ff5-77706e5c9f72.gif)

**Comment by JanKoehnlein** [comment] 2017-10-24 13:13
We should add selection indication

**Comment by JanKoehnlein** [comment] 2017-10-27 13:41
"Center" and "Fit to Screen" in sprotty refer to the selection, and if nothing is selected to the entire diagram. That's why I think the real problem is the missing selection indication.

**Comment by JanKoehnlein** [comment] 2017-10-27 13:42
Closing this as a dupe of #25

**Closed by JanKoehnlein** 2017-10-27 13:42 UTC
